peeratmac/game-time

- src/index.html
Boiler plate to include modal areas, and jquery linked. Let me know what you think. @peeratmac @VPAbraham
> Add html boiler plate

- src/Game.js
- test/Game-test.js
co-authored by @VPAbraham, @peeratmac via zoom video call.
> Add boiler/methods/testing for game class

- test/Round-test.js
co-authored by @VPAbraham @peeratmac via zoom video call.
> Add boiler for round testing

- src/Puzzle.js
- src/data/sample-data.js
- test/Puzzle-test.js
- test/Round-test.js
co-authored by @VPAbraham @peeratmac via zoom video call.
> Puzzle class

- src/Round.js
- test/Round-test.js
1. I fixed the case issue for guessing letters, we were only getting a single index in our indices array if the guessed letter appeared in the correct-answer as both lower and upper case.
2. I moved the array resets to endRound() for SRP.
3. I changed check solve to compare the length of our correct answer indices array to an array of the letters in the correct answer with the spaces pulled out.
Let me know what you think, and if there is anything that I could clarify/doesn't make sense why I did it the way I did.
> Round branch

- src/Wheel.js
- test/Round-test.js
- test/Wheel-test.js
Made Wheel class and a couple tests.  It has a method to randomize the output from the array of wheel value in the sample-data dataset and the output is also set to a value on the constructor.  We can remove this later but I wasn't sure if we'd be 'spinning' the wheel by just running the method or instantiating a new wheel each time. Let me know what you guys think.
> Wheel class

- src/Puzzle.js
- src/Round.js
- src/Turn.js
- src/Wheel.js
- test/Puzzle-test.js
- test/Round-test.js
- test/Turn-test.js
- test/Wheel-test.js
co-Authored-by: Peerat Sukcharoenyingyong <peeratmac@icloud.com>
co-Authored-by: Chris Basham <chrisdbasham317@gmail.com>
@khalidwilliams
@brittanystoroz
> Fix methods in round, wheel, turn, and puzzle to pass all tests

- src/Player.js
- test/Players-test.js
All tests are passing as of this commit for Players
> Update and refactor Players class along with all the tests for Playr

- src/index.html
Should not affect the DOM appension much if at all.
> Add header element and link some fonts to document

- src/Game.js
- src/Player.js
- src/Round.js
- test/Game-test.js
- test/Player-test.js
- test/Round-test.js
@peeratmac @VPAbraham @khalidwilliams @.DS_Storoz
This is mainly the refactor we decided to do on the Game, Round, and Player class. A lot of the changes involved storing the players w/ their data as props in Game and Round, and then changing the class methods to alter only the data within that class. The other part to that change was changing the methods to utilize arguments/parameters more rather that using one classes methods to change another classes props.
> Game class refrac

- src/Game.js
- src/domUpdates.js
- src/index.html
- src/index.js
Added some p elements for items to load on screen. Puzzle loads in readable form, and the category does as well. I think we need to move these items into domUpdates though.
> Add dom interaction for player names/puzzle loading

- src/Wheel.js
- src/css/base.scss
- src/domUpdates.js
- src/index.html
- src/index.js
- test/Wheel-test.js
@VPAbraham @chrisdbasham317 I will let you guys know when I am finished for the night to review again.  This is currently a work in progress.
> Make the modal shows up on page load to enter in 3 players name

- src/Wheel.js
- src/css/base.scss
- src/domUpdates.js
- src/index.html
- src/index.js
- test/Wheel-test.js
Revert is causing issues with pushing new changes to css and index.
> Revert "Make the modal shows up on page load to enter in 3 players name"

- src/css/base.scss
- src/index.html
New styling and index changes.
> Continue styling, added round board elements

- src/css/base.scss
- src/index.html
Some styling to touch up modal so we can continue to work on DOM interaction with it.
> Style game start modal

- .vscode/launch.json
- src/Game.js
- src/Player.js
- src/Round.js
- src/domUpdates.js
- src/index.html
- src/index.js
When user submit the form in the modal at start, that info gets updated in the DOM.  Spin value is now displayed accordingly, randomize from the wheel data.
@VPAbraham @chrisdbasham317  changes are still being made, I would let you guys know once this is ready to be reviewed.  It probably won't be until later tonight.  I will comment and tag you both again!
> Add HTML section for player name/scores/total money.

- .vscode/launch.json
- src/Game.js
- src/Player.js
- src/Round.js
- src/domUpdates.js
- src/index.html
- src/index.js
Playable up through the end of Round 4.  Bonus round functionalities will still have to be added.
> Game play through rounds with update round number display and new prompt for subsequent rounds

- .vscode/launch.json
- src/Game.js
- src/Player.js
- src/Round.js
- src/domUpdates.js
- src/index.html
- src/index.js
When puzzle is solved, round money is added to total money for the winner. 
Next up:  need to reset round money to 0 in the DOM for all players.
> Update total money after puzzle is solved

- src/css/base.scss
- src/index.html
Sending this up before making some changes to class names.
> Style new elements and make font-sizes and footer more responsive

- src/css/base.scss
- src/index.html
Added some HTML elements and styling to get the spinner values updating in a clear way.
> Styling on spinner board

- README.md
- src/Game.js
- src/Round.js
- src/domUpdates.js
- src/index.js
Will need to add screenshots and working product gifs once our product is ready.
> Readme Documentation initial update

- src/Round.js
- src/domUpdates.js
- src/index.html
- src/index.js
And it gets update with each guess, and clear when the round has ended.
> Users can now see letters they have already used display on the DOM

- src/domUpdates.js
- src/index.html
- src/index.js
Turn section is in the Up Now: area.  We are showing the name of the current player right now, can change to show player number too, if preferred.
> Add category section and add ability for users to know whose turn it is

- src/Wheel.js
- src/index.js
Added data fetching for the puzzle data and the wheel data.
> Incorporate data fetching to app

- src/Game.js
- src/domUpdates.js
- src/index.js
Added field validation for player names before the game can start. Also added clear field method for player guess field.
> Player fields

- src/css/base.scss
- src/domUpdates.js
- src/index.html
Create and style Start New Game button. Fix some appension bugs with puzzles with symbols.
> Create and style Start New Game button. Fix some appension bugs with puzzles with symbols

- src/Round.js
- src/css/base.scss
- src/index.html
- src/index.js
Adds modal to input a solution. If correct, a new round/puzzle begin. If not, another modal that states 'INCORRECT' appears.
> Full solution

- src/domUpdates.js
- src/index.js
Broke up the letter guess jquery function to handle the major calculations. The rest I rewrote into consonant/vowel specific functionality. Buying vowels costs a flat rate of $100 regardless of how many occurences of the bought vowel. I see that this PR can't be merged, but there are other PR's waiting in the queue. I'll resolve whatever conflicts there are with this one after the others go in.
> Buy vowel guess consonant

- src/Game.js
- src/index.js
- test/Game-test.js
Refactor/restructure of game class and game-test
> Remove unused methods/tests for game class/test
